### ISSUE TITLE
スニークを行うとアバターの表示がおかしくなる

### ISSUE THREAD

**Issue by Shinryoku-lg** [Gakuto1112/CatMaid#3]
タイトルの通りです。シングルでの発生を確認しました。
Minecraftのバージョン：1.19.4
Figuraのバージョン：0.1.0-rc.14
その他Mod：
fabric-api-0.77.0+1.19.4
modmenu-6.1.0-rc.4

<details>
<summary>エラー内容</summary>
[02:52:11] [Render thread/ERROR]: 
org.luaj.vm2.LuaError: scripts.arms:9 attempt to call a nil value
stack traceback:
	scripts.arms:9: in function <scripts.arms:8>
	[Java]: in ?
	at org.luaj.vm2.LuaValue.checkmetatag(LuaValue.java:3906) ~[com_github_moonlight-mc_luaj_lua.0.5-figura-73cd360e46cb5368.jar:?]
	at org.luaj.vm2.LuaValue.callmt(LuaValue.java:2356) ~[com_github_moonlight-mc_luaj_lua.0.5-figura-73cd360e46cb5368.jar:?]
	at org.luaj.vm2.LuaValue.call(LuaValue.java:1734) ~[com_github_moonlight-mc_luaj_lua.0.5-figura-73cd360e46cb5368.jar:?]
	at org.luaj.vm2.LuaClosure.execute(LuaClosure.java:445) ~[com_github_moonlight-mc_luaj_lua.0.5-figura-73cd360e46cb5368.jar:?]
	at org.luaj.vm2.LuaClosure.onInvoke(LuaClosure.java:224) ~[com_github_moonlight-mc_luaj_lua.0.5-figura-73cd360e46cb5368.jar:?]
	at org.luaj.vm2.LuaClosure.invoke(LuaClosure.java:216) ~[com_github_moonlight-mc_luaj_lua.0.5-figura-73cd360e46cb5368.jar:?]
	at org.moon.figura.lua.api.event.LuaEvent.call(LuaEvent.java:65) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at org.moon.figura.avatar.Avatar.lambda$run$3(Avatar.java:300) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at org.moon.figura.avatar.Avatar.run(Avatar.java:327) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at org.moon.figura.avatar.Avatar.tickEvent(Avatar.java:346) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at org.moon.figura.avatar.Avatar.tick(Avatar.java:240) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at org.moon.figura.avatar.AvatarManager.tickLoadedAvatars(AvatarManager.java:64) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at org.moon.figura.FiguraMod.tick(FiguraMod.java:81) ~[figura-0.1.0-rc.14+1.19.4.jar:?]
	at net.minecraft.class_310.handler$zkc000$figura$startTick(class_310.java:6134) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1180) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
[02:52:11] [Render thread/INFO]: [System] [CHAT] [error] username : scripts.arms:9 attempt to call a nil value\nstack traceback:\n  scripts.arms:9: in function <scripts.arms:8>\nscript:\n  ArmsClass.isSneaking = player:getPose() == "CROUCHING" and not player:isFlying() and not rendere [...]
</details>

**Comment by Gakuto1112** [comment]
ご報告ありがとうございます。先ほど該当のエラーを修正しました。ご不便をおかけしました。
